version: '2'
services:

  # toma como base la imagen definida en Dockerfile + las modificaciones
  # propias de este + redireccion de puertos desde aqui
  node-red:
    build: ./img-node-red/ .
    volumes:
      - ./img-node-red/storage/:/home/src/node_modules/node-red/red/runtime/storage/
    ports: # huesped:anfitrion
      - "1880:1880"
    links:
      - storage-api

  storage-api:
    build: ./img-storage-api/ .
    ports: # huesped:anfitrion
      - "3000:3000"
    depends_on:
      - mongo

  # proxy inverso
  nginx:
    build: ./img-proxy/ .
    volumes:
      - ./img-proxy/nginx/:/etc/nginx/
    ports: # huesped:anfitrion
      - "80:80"
    links:
      - node-red
      - mqtt

  mongo:
    image: "mongo"
    ports: # huesped:anfitrion
      - "27017:27017"

  mqtt:
    image: eclipse-mosquitto
    ports: # huesped:anfitrion
      - "1883:1883"
      - "9001:9001"
