version: '2'
services:

  # toma como base la imagen definida en Dockerfile + las modificaciones
  # propias de este + redireccion de puertos desde aqui
  node-red:
    build: ./img-nred-base/ .
    volumes:
      - ./img-nred-base/storage/:/home/src/node_modules/node-red/red/runtime/storage/
    depends_on:
      - storage-api

  storage-api:
    build: ./img-storage-api/ .
    depends_on:
      - mongo

  # proxy inverso
  nginx:
    build: ./img-proxy/ .
    volumes:
      - ./img-proxy/nginx/:/etc/nginx/
    ports: # huesped:anfitrion
      - "80:80"
      #- "9229:9229"
    links:
      - node-red
      - mqtt

  mongo:
    image: "mongo"
    ports: # huesped:anfitrion
      - "27017:27017"

  mqtt:
    build: ./img-mosquitto/ .
    volumes:
      - ./img-mosquitto/mosquitto/:/mosquitto
