version: '2'
services:
  web:
    build: .
    ports: # huesped:anfitrion
      - "3001:3001"
    links:
      - mongo
  mongo:
    image: "mongo"
    ports: # huesped:anfitrion
      - "27017:27017"
